<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ProdutosAPI.Pedidos</RootNamespace>
    <AssemblyName>Pedidos</AssemblyName>
  </PropertyGroup>
  <!-- Exclude Domain — compiled in Pedidos.Domain.csproj -->
  <ItemGroup>
    <Compile Remove="Domain/**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Domain/Pedidos.Domain.csproj" />
    <ProjectReference Include="../Shared/Common/Shared.Common.csproj" />
    <ProjectReference Include="../Shared/Data/Shared.Data.csproj" />
    <ProjectReference Include="../Catalogo/Catalogo.Domain/Catalogo.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>
</Project>
